src/Entity/Servico.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ServicoRepository")
 */
class Servico
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Campo título não pode ser branco")
     * @Assert\Length(
     *     min="40",
     *     minMessage="o Campo título de ter no Mínimo de {{ limit }} caracteres",
     *     max="255",
     *     maxMessage="o Campo título de ter no Máximo de {{ limit }} caracterers"
     * )
     */
    private $titulo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"titulo"}, updatable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="decimal", precision=2)
     */
    private $valor;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Campo descrição não pode ser branco")
     */
    private $descricao;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $informacoes_adicionais;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Campo Prazo de Entrega não pode ser branco")
     */
    private $prazo_entrega;

    /**
     * @ORM\Column(type="string", length=1,
     *     options={
     *     "comment": "Usar P para publicado, A para Em Análise, I para Inativo, E para Excluído e R para Rejeitado"})
     * @Assert\Choice(choices={"P", "A", "I", "E", "R"})
     */
    private $status;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Gedmo\Timestampable(on="create")
     */
    private $data_cadastro;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     * @Gedmo\Timestampable(on="update")
     */
    private $data_alteracao;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="Selecione uma imagem para o job")
     * @Assert\Image(
     *     mimeTypes={"image/*"},
     *     mimeTypesMessage="Tipo de Arquivo Inválido",
     *     maxHeight="1000",
     *     maxHeightMessage="Máximo de 1000px de altura",
     *     minHeight="400",
     *     minHeightMessage="Mínimo de 400px de altura",
     *     maxWidth="1000",
     *     maxWidthMessage="Máximo de 1000px de largura",
     *     minWidth="400",
     *     minWidthMessage="Mínimo 400px de largura"
     * )
     */
    private $imagem;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Categoria", mappedBy="servicos")
     */
    private $categorias;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Usuario", inversedBy="servicos")
     */
    private $usuario;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contratacoes", mappedBy="servico")
     */
    private $contratacoes;

    public function __construct()
    {
        $this->categorias = new ArrayCollection();
        $this->contratacoes = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getValor()
    {
        return $this->valor;
    }

    public function setValor($valor): self
    {
        $this->valor = $valor;

        return $this;
    }

    public function getDescricao(): ?string
    {
        return $this->descricao;
    }

    public function setDescricao(string $descricao): self
    {
        $this->descricao = $descricao;

        return $this;
    }

    public function getInformacoesAdicionais(): ?string
    {
        return $this->informacoes_adicionais;
    }

    public function setInformacoesAdicionais(?string $informacoes_adicionais): self
    {
        $this->informacoes_adicionais = $informacoes_adicionais;

        return $this;
    }

    public function getPrazoEntrega(): ?int
    {
        return $this->prazo_entrega;
    }

    public function setPrazoEntrega(int $prazo_entrega): self
    {
        $this->prazo_entrega = $prazo_entrega;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus($status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getDataCadastro(): ?\DateTimeImmutable
    {
        return $this->data_cadastro;
    }

    public function setDataCadastro(\DateTimeImmutable $data_cadastro): self
    {
        $this->data_cadastro = $data_cadastro;

        return $this;
    }

    public function getDataAlteracao(): ?\DateTimeImmutable
    {
        return $this->data_alteracao;
    }

    public function setDataAlteracao(?\DateTimeImmutable $data_alteracao): self
    {
        $this->data_alteracao = $data_alteracao;

        return $this;
    }

    public function getImagem()
    {
        return $this->imagem;
    }

    public function setImagem($imagem): self
    {
        $this->imagem = $imagem;

        return $this;
    }

    /**
     * @return Collection|Categoria[]
     */
    public function getCategorias(): Collection
    {
        return $this->categorias;
    }

    public function addCategoria(Categoria $categoria): self
    {
        if (!$this->categorias->contains($categoria)) {
            $this->categorias[] = $categoria;
            $categoria->addServico($this);
        }

        return $this;
    }

    public function removeCategoria(Categoria $categoria): self
    {
        if ($this->categorias->contains($categoria)) {
            $this->categorias->removeElement($categoria);
            $categoria->removeServico($this);
        }

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * @return Collection|Contratacoes[]
     */
    public function getContratacoes(): Collection
    {
        return $this->contratacoes;
    }

    public function addContrataco(Contratacoes $contrataco): self
    {
        if (!$this->contratacoes->contains($contrataco)) {
            $this->contratacoes[] = $contrataco;
            $contrataco->setServico($this);
        }

        return $this;
    }

    public function removeContrataco(Contratacoes $contrataco): self
    {
        if ($this->contratacoes->contains($contrataco)) {
            $this->contratacoes->removeElement($contrataco);
            // set the owning side to null (unless already changed)
            if ($contrataco->getServico() === $this) {
                $contrataco->setServico(null);
            }
        }

        return $this;
    }

}

src/Entity/Usuario.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Serializable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsuarioRepository")
 * @UniqueEntity("email", message="Esse email já esta em uso!")
 */
class Usuario implements UserInterface, Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(message="Campo nome não pode ser vazio")
     */
    private $nome;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Campo email não pode ser vazio")
     * @Assert\Email(message="Informe um email válido.")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message="Informe sua senha")
     */
    private $senha;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $token;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Gedmo\Timestampable(on="create")
     */
    private $data_cadastro;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     * @Gedmo\Timestampable(on="update")
     */
    private $data_alteracao;

    /**
     * @ORM\Column(type="json_array")
     */
    private $roles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Servico", mappedBy="usuario")
     */
    private $servicos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contratacoes", mappedBy="cliente")
     */
    private $compras;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Contratacoes", mappedBy="freelancer")
     */
    private $vendas;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\DadosPessoais", cascade={"persist", "remove"})
     */
    private $dados_pessoais;


    public function __construct()
    {
        $this->status = false;
        $this->servicos = new ArrayCollection();
        $this->compras = new ArrayCollection();
        $this->vendas = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getNome(): ?string
    {
        return $this->nome;
    }

    public function setNome(string $nome): self
    {
        $this->nome = $nome;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSenha(): ?string
    {
        return $this->senha;
    }

    public function setSenha(string $senha): self
    {
        $this->senha = $senha;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): self
    {
        $this->token = $token;

        return $this;
    }

    public function getDataCadastro(): ?\DateTimeImmutable
    {
        return $this->data_cadastro;
    }

    public function setDataCadastro(\DateTimeImmutable $data_cadastro): self
    {
        $this->data_cadastro = $data_cadastro;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDataAlteracao()
    {
        return $this->data_alteracao;
    }

    /**
     * @param mixed $data_alteracao
     * @return Usuario
     */
    public function setDataAlteracao($data_alteracao)
    {
        $this->data_alteracao = $data_alteracao;
        return $this;
    }

    public function setRoles($roles): self
    {
        $this->roles[] = $roles;
        return $this;
    }

    public function limparRoles(): self
    {
        $this->roles = [];
        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     * <code>
     * public function getRoles()
     * {
     *     return array('ROLE_USER');
     * }
     * </code>
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return  (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string The password
     */
    public function getPassword(): string
    {
        return $this->senha;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername(): string
    {
        return $this->email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        return null;
    }

    /**
     * @return Collection|Servico[]
     */
    public function getServicos(): Collection
    {
        return $this->servicos;
    }

    public function addServico(Servico $servico): self
    {
        if (!$this->servicos->contains($servico)) {
            $this->servicos[] = $servico;
            $servico->setUsuario($this);
        }

        return $this;
    }

    public function removeServico(Servico $servico): self
    {
        if ($this->servicos->contains($servico)) {
            $this->servicos->removeElement($servico);
            // set the owning side to null (unless already changed)
            if ($servico->getUsuario() === $this) {
                $servico->setUsuario(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contratacoes[]
     */
    public function getCompras(): Collection
    {
        return $this->compras;
    }

    public function addCompra(Contratacoes $compra): self
    {
        if (!$this->compras->contains($compra)) {
            $this->compras[] = $compra;
            $compra->setCliente($this);
        }

        return $this;
    }

    public function removeCompra(Contratacoes $compra): self
    {
        if ($this->compras->contains($compra)) {
            $this->compras->removeElement($compra);
            // set the owning side to null (unless already changed)
            if ($compra->getCliente() === $this) {
                $compra->setCliente(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contratacoes[]
     */
    public function getVendas(): Collection
    {
        return $this->vendas;
    }

    public function addVenda(Contratacoes $venda): self
    {
        if (!$this->vendas->contains($venda)) {
            $this->vendas[] = $venda;
            $venda->setFreelancer($this);
        }

        return $this;
    }

    public function removeVenda(Contratacoes $venda): self
    {
        if ($this->vendas->contains($venda)) {
            $this->vendas->removeElement($venda);
            // set the owning side to null (unless already changed)
            if ($venda->getFreelancer() === $this) {
                $venda->setFreelancer(null);
            }
        }

        return $this;
    }

    public function getDadosPessoais(): ?DadosPessoais
    {
        return $this->dados_pessoais;
    }

    public function setDadosPessoais(?DadosPessoais $dados_pessoais): self
    {
        $this->dados_pessoais = $dados_pessoais;

        return $this;
    }

    /**
     * String representation of object
     * @link http://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        return serialize([
            $this->getId(),
            $this->getNome(),
            $this->getEmail(),
            $this->getSenha(),
            $this->getRoles(),
            $this->getStatus()
        ]);
    }

    /**
     * Constructs the object
     * @link http://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->nome,
            $this->email,
            $this->senha,
            $this->roles,
            $this->status,
            ) = unserialize($serialized, ['allowed_class' => false]);
    }
}

src/AdminBundle/Controller/DefaultController.php
<?php
/**
 * Created by PhpStorm.
 * User: Claus Perbony
 * Date: 15/05/2018
 * Time: 14:30
 */

namespace App\AdminBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="admin_default")
     * @Template("@Admin/default/index.html.twig")
     */
    public function index()
    {
//        // Set some html and get the service
//        $html = '<h1>Sample Title</h1><p>Lorem Ipsum</p>';
//        $dompdf = $this->get('dompdf');
//        // Stream the pdf to the browser
//        $dompdf->streamHtml($html, "document.pdf");
    }
}

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Microjobs{% endblock %}

{% block body %}
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Album example</h1>
            <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
                etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
            <p>
                <a href="#" class="btn btn-primary my-2">Main call to action</a>
                <a href="#" class="btn btn-secondary my-2">Secondary action</a>
            </p>
        </div>
    </section>

    <div class="album py-5 bg-light">

        <div class="container">
            <h1>Últimos Microjobs</h1>
            <div class="row">
                {% for job in microjobs %}
                    <div class="col-md-3">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="{{ asset(caminho_imagens ~ job.imagem) }}"
                                 alt="{{ job.titulo }}">
                            <div class="card-body">
                                <p class="card-text">
                                    <a href="{{ path('visualizar_job', {"slug": job.slug}) }}" class="btn-link">{{ job.titulo }}</a>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <p class="badge badge-info">R$ {{ job.valor|number_format(2, ", ", ".") }}</p>
                                    <small class="text-muted">{{ job.dataCadastro|date("d/m/Y") }}</small>
                                </div>
                                <small class="text-muted float-right">{{ job.usuario.nome }}</small>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>
{% endblock %}

templates/default/painel.html.twig
{% extends 'base_painel.html.twig' %}

{% block title %}Painel do usuário - {% endblock %}

{% block topo_painel %}
    <h1>Painel do usuário</h1>
    <hr>
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <h3 class="card-header text-center  text-white bg-info">Saldo Total</h3>
                <div class="card-body">
                    <h4 class="text-center text-danger">R$ 130,00</h4>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <h3 class="card-header text-center  text-white bg-danger">Saldo não liberado</h3>
                <div class="card-body">
                    <h4 class="text-center text-danger">R$ 40,00</h4>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <h3 class="card-header text-center text-white bg-success">Saldo disponível</h3>
                <div class="card-body">
                    <h4 class="text-center text-danger">R$ 90,00</h4>
                </div>
            </div>
        </div>
    </div>
    {%  endblock %}

{% block body_painel %}
    <!-- TODO: Refatorar usando includes -->
    <div class="row mb-2">
        <div class="col-md-4">
            <form action="" name="form_filtro_status">
                <select name="busca_filtro" id=""
                        class="form-control-sm form-control float-left"
                        onchange="document.form_filtro_status.submit()"
                >
                    <option value="" {% if status == "" %}selected="selected"{% endif %}>Filtrar Microjob por
                    </option>
                    <option value="P" {% if status == "P" %}selected="selected"{% endif %}>Publicado</option>
                    <option value="A" {% if status == "A" %}selected="selected"{% endif %}>Em Análise</option>
                    <option value="I" {% if status == "I" %}selected="selected"{% endif %}>Inativos</option>
                    <option value="E" {% if status == "E" %}selected="selected"{% endif %}>Excluídos</option>
                    <option value="R" {% if status == "R" %}selected="selected"{% endif %}>Rejeitados</option>
                </select>
            </form>
        </div>
        <div class="offset-4 col-md-4">
            <a href="{{ path("cadastrar_job") }}" class="btn btn-block btn-primary float-right">Cadastrar
                MicroJob</a>
        </div>
    </div>
    <hr>
    {% for job in microjobs %}
        <div class="card mb-2">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-1">
                        <img width="60" src="{{ asset(caminho_imagens ~ job.imagem) }}" alt="{{ job.titulo }}">
                    </div>
                    <div class="col-md-6">
                        <h5>{{ job.titulo }}</h5>
                    </div>
                    <div class="col-md-2">
                        <p>{{ job.dataCadastro|date('d/m/Y') }}</p>
                    </div>
                    <div class="col-md-1">
                        {% if job.status == "A" %}
                            <p class="badge badge-warning text-white">Em análise</p>
                        {% elseif job.status == "P" %}
                            <p class="badge badge-success text-white">Publicado</p>
                        {% elseif job.status == "I" %}
                            <p class="badge badge-secondary text-white">Inativo</p>
                        {% elseif job.status == "E" %}
                            <p class="badge badge-danger text-white">Excluído</p>
                        {% elseif job.status == "R" %}
                            <p class="badge badge-dark text-white">Rejeitado</p>
                        {% else %}
                            <p class="badge badge-light">N/A</p>
                        {% endif %}
                    </div>
                    <div class="col-md-2">
                        {% if job.status != "E" %}
                            <a href="{{ path("excluir_servico", {"id": job.id}) }}"
                               class="float-right btn btn-danger btn-sm bt_excluir_servico"><i
                                        class="fa fa-trash-alt"></i></a>
                            {#<a href="" class="float-right btn btn-success btn-sm mr-1"><i class="fa fa-pencil-alt"></i></a>#}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="card mb-2">
            <div class="card-body">
                <div class="alert alert-warning">Nenhum serviço encontrado</div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            $(".bt_excluir_servico").click(function (ev) {
                ev.preventDefault();

                if (confirm("Deseja excluir esse job?")) {
                    var url = $(this).prop("href");
                    window.location = url;
                }
            });
        });
    </script>
{% endblock %}

templates/default/visualizar-job.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <h2>{{ job.titulo }}</h2>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-7">
                <div class="row">
                    <div class="col-md-12">
                        <img src="{{ asset(caminho_imagens ~ job.imagem)  }}" alt="{{ job.titulo }}" class="img-fluid img-thumbnail">
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12 text-justify">
                        <h3>Descrição</h3>
                        {{ job.descricao|nl2br }}

                    </div>
                </div>
                {% if job.informacoesAdicionais %}
                    <div class="row mt-3">
                        <div class="col-md-12 text-justify">
                            <h3>Informações adicionais</h3>
                            {{ job.informacoesAdicionais|nl2br }}
                        </div>
                    </div>
                {% endif %}
                <hr>
                <div class="row">
                    <div class="col-md-12">
                        {%  for categoria in job.categorias %}
                        <span class="badge badge-secondary">{{ categoria.nome }}</span>
                        {%  endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Contratar serviço</h3>
                    </div>
                    <div class="card-body">
                        <h4 class="display-3 text-center text-danger text-lg-center mb-4">R$ {{ job.valor|number_format(2, ",", ".") }} </h4>
                        <a href="{{ path('tela-pagamento', {"id": job.id, 'slug': job.slug}) }}" class="btn btn-lg btn-block btn-outline-success">Contratar</a>
                    </div>
                </div>
                <div class="card mt-3">
                    <div class="card-header">
                        <h3 class="text-center">Detalhes do Profissional</h3>
                    </div>
                    <div class="card-body">
                        <img class="rounded float-left mr-3" src="{{ vich_uploader_asset(job.usuario.dadosPessoais, 'foto_file') | imagine_filter('thumb_profile_job') }}" alt="">
                        <h4>{{ job.usuario.nome }}</h4>
                        <hr>
                        <div class="clearfix"></div>
                        <div class="mt-4">
                            {{ job.usuario.dadosPessoais.curriculo | nl2br }}
                        </div>
                        <p><strong>Cidade: </strong>{{ job.usuario.dadosPessoais.cidade }}/{{ job.usuario.dadosPessoais.estado }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block title %}

    {{ job.titulo }} -

{% endblock %}